version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  url-shortener:
    build:
      context: .
      dockerfile: url-shortener/Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - "9090:9090"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/url_shortener
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATA_REDIS_HOST: redis

  log-cli:
    build:
      context: .
      dockerfile: log-cli/Dockerfile
#    volumes:
#      - ./sample-data:/app/samples
    entrypoint: ["java", "-jar", "app.jar"]