spring:
  application:
    name: url-shortener
  mvc:
    throw-exception-if-no-handler-found: true
    web:
      resources:
        add-mappings: true

  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener
    username: postgres
    password: sherif
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/url_shortener
      pool-name: url-shortener-pool
      connection-timeout: 30000
      pool-size: 10
      idle-timeout: 30
      max-lifetime: 1800000
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}
      leak-detection-threshold: 60000
      minimum-idle: 10
      schema: public

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/url_shortener
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: public
    out-of-order: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2s

  cache:
    type: redis
    redis:
      time-to-live: 10m
      cache-null-values: false

server:
  port: 9090

app-config:
  short-url:
    expiry-minutes: 60
    max-create-retry: 5
  thread-config:
    core-pool-size: 5
    max-pool-size: 10
    queue-capacity: 100
  cache-config:
    ttl-minutes: 10
  rate-limit-config:
    limit-period-minutes: 1
    limit-token: 10
    limit-capacity: 10


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    org.flywaydb: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    display-request-duration: true
    tryItOutEnabled: true
    filter: true